### PR TITLE
Update isort for compatibility with Poetry

### PR DESCRIPTION
**Pull request by jobselko**
Fixes a broken githook

### CODE REVIEW

**Review by Elkasitu — APPROVED** [review]
The change LGTM as it's a minor version bump, but could you document the source of the incompatibility in your commit message? i.e. why is 5.12 required?

**Comment by jobselko** [comment]
@Elkasitu When running `git commit`, I got:
```
RuntimeError: The Poetry configuration is invalid:
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

So, would be something like this sufficient? `Update isort for compatibility with Poetry (https://github.com/PyCQA/isort/commit/0d219a6e0b49b7f84ef0702b2387d5e14299bb8e)`

**Comment by Elkasitu** [comment]
Yes, just a link to the isort issue/PR in the commit body is sufficient, crazy that isort depends on bits from poetry

**Review by JakubFrejlach — APPROVED** [review]

**Comment by jobselko** [comment]
FTR, I have opened a new PR because it seems that pull requests from fork do not trigger GitLab's CI.

**Comment by jobselko** [comment]
Closing.

**Pull request closed without merging**
