### PR TITLE
Add multi-db routing

### PR DESCRIPTION
**Pull request by Elkasitu**
These changes introduce the following:

* The removal of the whitenoise library as it's not being actively used by anything in our codebase.
* The implementation of a custom Django Database Router for weighted load balancing of read operations.
* The application of said router to staging and production.

### CODE REVIEW

**Review by osoukup — APPROVED** [review]
Interesting! LGTM

**Review by costaconrado — APPROVED** [review]
LGTM.

**Comment by Elkasitu** [comment]
Actually should probably hold off on this as prod isn't deployed to production yet...

**Review by JakubFrejlach — APPROVED** [review]

**Comment by Elkasitu** [comment]
@RedHatProductSecurity/osidb-devs if you could re-review, I have decided to have our own database router as:

* It's quite straightforward to implement
* Gives us more power in the way that we do load balancing
* Makes for one less dependency (previously the plan was to use django-multidb-router which is pretty unmaintained)

**Review by osoukup — APPROVED** [review]
As far as I can understand :smile: this LGTM

**Comment by JakubFrejlach** [comment]
As https://github.com/RedHatProductSecurity/osidb/pull/351 brings a new GH action check which checks for schema with osidb-bindings compatibility, make sure you rebase this PR on top of the master branch so mentioned GH action may be triggered if this PR makes changes to `openapi.yml`.

**Comment by JimFuller-RedHat** [comment]
what is the status of this PR ?

**Comment by osoukup** [comment]
> what is the status of this PR ?

Good question. It seems that the code is already well accepted but was never rebased. I hope that nothing changed in a way that it would not be applicable or compatible any more as it is already quite some time waiting here but I think that nothing else in this regard has changed.

**Comment by JimFuller-RedHat** [comment]
@osoukup I will review this week

**Comment by JimFuller-RedHat** [comment]
due to rebasing fun - closing this and reraising PR here https://github.com/RedHatProductSecurity/osidb/pull/492

**Pull request closed without merging**
