### PR TITLE
update the tests to reflect the GitLab URL change

### PR DESCRIPTION
**Pull request by osoukup**
so they do not fail with .env with up-to-date GitLab URLs

### CODE REVIEW

**Comment by osoukup** [comment]
I updated the product definitions and PS constants cassettes. The product definitions data also changed in the meantime so I had to slightly update the related tests too. With this you can have up-to-date CEE GitLab URLs in your **.env** file and the tests will not fail.

**Review by jobselko — APPROVED** [review]
LGTM. Do we know why CI tests are failing?

**Comment by osoukup** [comment]
> LGTM. Do we know why CI tests are failing?
> 
> Edit: It seems we have to update vars also in CI.

@jobselko correct.

**Comment by skontar** [comment]
All tests pass for me. Thanks!

**Review by skontar — APPROVED** [review]

**Comment by osoukup** [comment]
I updated the URLs in the project secrets here in GitHub and the originally failing tests are not failing any more but some new and seemingly unrelated test fails now :smile: fun ahead.

**Pull request merged**
