### PR TITLE
merge 2.3.2 to master

### PR DESCRIPTION
**Pull request by osoukup**
after release merge

### CODE REVIEW

**Review by Elkasitu — APPROVED** [review]
LGTM, I'd do a `git pull --rebase origin master` to remove that last merge commit 😜

**Comment by osoukup** [comment]
@Elkasitu that would however bring all the master before 2.3.2 release which does not seem correct to me. That would make stuff already released appear after not yet released stuff. Is it really what we want?

**Comment by Elkasitu** [comment]
Well the order of commits on master is not representative of the commits present in a given version, rebase is what we've done in the past but you can leave the merge commit if you prefer

**Comment by osoukup** [comment]
@Elkasitu I agree that it would be no issue on master but if I rebase the branch I will change it in a way that if we potentially released a patch 2.3.3 it would also contain unrelated commits from master.

**Comment by Elkasitu** [comment]
@osoukup if we need to release a 2.3.3 patch we'd base it off of the `2.3.2` tag as described in the patch release [documentation](https://git.prodsec.redhat.com/devops/osidb-ops/-/blob/master/README.md#deploy-patch-version-mid-sprint), meaning that nothing merged into master would get in

**Review by costaconrado — APPROVED** [review]
LGTM. Versions and Jira numbers make sense.

**Pull request merged**
