### PR TITLE
remove daily monitoring email for failed tasks / collectors

### PR DESCRIPTION
**Pull request by osoukup**
This mostly reverts commit [89cbdcd1ff86273882d48033371078f29d23be00](https://github.com/RedHatProductSecurity/osidb/commit/89cbdcd1ff86273882d48033371078f29d23be00). It removes all the emailing functionality and the DB cleaning task. Most importantly it changes **CELERY_RESULT_BACKEND** back to **redis**.

Closes OSIDB-1215

### CODE REVIEW

**Comment by osoukup** [comment]
@Elkasitu this should be tested before I merge it. I think I should follow https://gitlab.corp.redhat.com/product-security/dev/osidb-ops/-/blob/master/README.md?ref_type=heads#manual-deployment-mp and manually deploy stage from this commit. Is it the correct approach?

**Review by Elkasitu — CHANGES_REQUESTED** [review]
Thanks for doing this!

Partially reverting the following is necessary: https://github.com/RedHatProductSecurity/osidb/pull/296/files (mainly the stage/prod settings, the signal can stay) otherwise the results won't be stored in the correct backend in those environments /!\

You can also remove the following:

https://github.com/RedHatProductSecurity/osidb/pull/28/files#diff-935426a2f59d34e9506987404f8d78b5b5b43431694101f5be37ad65af4cf193R161-R173

And https://github.com/RedHatProductSecurity/osidb/pull/297/files

**Comment by Elkasitu** [comment]
> @Elkasitu this should be tested before I merge it. I think I should follow https://gitlab.corp.redhat.com/product-security/dev/osidb-ops/-/blob/master/README.md?ref_type=heads#manual-deployment-mp and manually deploy stage from this commit. Is it the correct approach?

Yes it is, just make sure the cluster is preprod (it should be the default), if you feel there's gaps in the documentation feel free to let me know / improve it 😃

**Comment by osoukup** [comment]
@Elkasitu thank you for the help with testing! I also think that your feedback should be all incorporated. Could you please have one more look?

**Review by Elkasitu — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
